FROM ubuntu

LABEL maintainer="Emerson Marques"

ENV WORKDIR /home/app/
ENV VERSAO_NODE 14.19.1
RUN mkdir -p $WORKDIR
WORKDIR $WORKDIR

RUN apt-get update && \
    apt-get install -y curl

# Instalar o NVM
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

# Configurar o NVM
ENV NVM_DIR /root/.nvm
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $VERSAO_NODE && nvm alias default $VERSAO_NODE"

# Instalar o Yarn
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && npm install -g yarn@1.22.10"

# Instalar o Node.js e o npm
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $VERSAO_NODE && nvm use $VERSAO_NODE && npm install -g npm@latest"

# Instalar o Prisma
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && npm install -g prisma@3.15.2"

# Restante do seu Dockerfile...



# SSH
RUN apt-get install -y openssh-server

RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

### CRIANDO USER APP E DANDO PODERES DE SUDO
RUN apt-get install -y sudo
RUN useradd -ms /bin/bash app
RUN adduser app sudo
RUN echo 'app:app' | chpasswd
RUN sudo echo 'app   ALL=(ALL:ALL) ALL' | sudo tee -a /etc/sudoers
RUN sudo echo "app   ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/app
# RUN sudo chmod 0440 /etc/sudoers.d/app


EXPOSE 22
VOLUME $WORKDIR
CMD ["/usr/sbin/sshd", "-D"]

####
# docker image build -t ubuntu -f ubuntu/Dockerfile ubuntu/
# sudo docker run -d -v $(pwd)app:/home/app -p 22221:22 --name ubuntu ubuntu
